import Head from "next/head";
import { useRouter } from "next/router";
import styled from "styled-components";
import GameCard from "../src/common/GameCard";

export default function Home() {
  const router = useRouter();
  const goExplore = () => {
    router.push("/explore");
  };
  return (
    <Wrap>
      <Head>
        <title>Ellixi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainText>
        Simply play
        <br />
        web3 <span>Game</span>
      </MainText>
      <ExploreButton onClick={goExplore}>Explore Game</ExploreButton>
      <GameList>
        <GameCard link="dino" name="dino" />
        <GameCard link="dino" name="dino" />
        <GameCard link="dino" name="dino" />
      </GameList>
    </Wrap>
  );
}
const Wrap = styled.div`
  display: flex;
  padding-top: 80px;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background-image: url("/assets/background.svg");
  background-repeat: no-repeat;
`;

const MainText = styled.div`
  font-weight: 700;
  font-size: 60px;
  line-height: 80px;
  margin: 20px 0px 50px 0px;
  span {
    background: linear-gradient(
      180deg,
      #da3a3a 0%,
      #da3a3a 0.01%,
      #9723ce 100%
    );
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
  }
`;

const ExploreButton = styled.div`
  width: 180px;
  height: 50px;
  display: flex;
  justify-content: center;
  align-items: center;

  background: linear-gradient(92.39deg, #d13750 9%, #ae2b9e 88.89%);
  border-radius: 30px;
`;

const GameList = styled.div`
  display: flex;
  flex-direction: row;
  width: 80%;
  margin: 0px 30px;
  padding: 50px 0px 50px 0px;
  overflow: scroll;
  -ms-overflow-style: none;

  ::-webkit-scrollbar {
    display: none;
  }
`;
